name:  main jobs that call sub-workflow
on: [push, workflow_dispatch]

jobs:
  call-workflow-passing-data:
    uses: test12345/.github/workflows/terraform_plan.yml@main
    with:
      directory: .github/labeler.yml
