
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      environment:
        description: Environment
        type: string
      aws_access_key_id:
        description: AWS access key id
        type: string
      aws_secret_key:
        description: AWS secret key
        type: string
      terraform_token:
        description: Terraform token required for terraform cloud
        type: string
    


jobs:
  runs-on: ubuntu-latest
  steps:
    - name: name: Export credentials and run terraform plan
      run: |
            cd ${{ inputs.directory }}
            echo -e "credentials "app.terraform.io" {\n  token = \"${{ inputs.terraform_token }}\"\n}" >> ~/.terraformrc
            export AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }}
            export AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_key }}
            # make tf-plan-${{ inputs.environment }}
